### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by alacerda** [keplerproject/luadoc#13]
Hi folks,

Is there any reason for not having releases avaliable?

Thanks,

**Comment by tomasguisasola** [comment]
Hi Alan

Yes, LuaDoc is a dead project.  You should use LDoc instead.

Regards,
Tomás

**Comment by rscarrasco** [comment]
Hey, if LuaDoc was superseded by LDoc, this should be stated in the README. I was preparing myself to collaborate with LuaDoc, which would have been in vain...

**Comment by hishamhm** [comment]
@rscarrasco Sorry about that. We now made it clear in the README. Hope to see you in [LDoc](http://github.com/stevedonovan/LDoc) development! :)
