### ISSUE TITLE
attempt to call field 'gfind' (a nil value)

### ISSUE THREAD

**Issue by kikito** [keplerproject/luadoc#16]
The `gfind` method was deprecated in Lua 5.1, and in Lua 5.2 (and LuaJIT, which is what I'm using) it doesn't exist any more - it was replaced by `gmach`.

If compatibility with Lua 5.0 isn't needed, then this can be fixed by replacing `gfind` by `gmatch` in `src/luadoc/doclet/html.lua` and `src/luadoc/util.lua`. If compatibility is desired, then in both of those files something like this is needed:

```
local gmatch = string.gfind or string.gmatch
...
for d in gmatch(...)
```

I can provide a PR for any of the two alternatives. Please let me know which one is preferred.

**Comment by tomasguisasola** [comment]
Hi Enrique

I think LDoc substituted this project.  Please check it.

Regards,
Tomás

2018-06-12 6:55 GMT-03:00 Enrique García Cota <notifications@github.com>:
